#!/usr/bin/env python3
"""Generate src/neon_log_cleanroom_data.inc -- anchor table for vector_log_neon.

Clean-room derived (2026-07-19): the table design, constants, and error
analysis were authored independently from first principles in an isolated
child-agent workspace, from a functional specification only, with zero access
to any existing log implementation. See docs/NEON_LOG_DERIVATION.md for the
mathematics and docs/NEON_LOG_DIVERGENCE_AUDIT.md for the point-by-point
comparison against the closest structural relative (ARM optimized-routines
advsimd log.c) confirming no shared expression. No third-party source.

Design (DERIVATION.md sections 2-4):
    x = 2^e * m, m in [1,2);  j = round(N*(m-1)) from the top mantissa bits.
    Per entry j (N = 128, 129 rows):
        R_j  = nearest double to 1/(1 + j/N)   (exact 1.0 at j=0, 0.5 at j=N)
        L_j  = -log(R_j) [- ln2 if j >= CUT]   stored as a compensated
               (L_hi, L_lo) pair, defined against the STORED double R_j so
               log m = L_j + [j>=CUT]*ln2 + log1p(m*R_j - 1) is an exact
               identity (the kernel's only residuals: one FMA rounding in
               t = m*R_j - 1, and the series truncation).
    CUT = round(N*(sqrt2-1)): entries with r_j >= ~sqrt2 fold -ln2 into L and
    the kernel bumps e by 1 (sqrt2 re-centering folded into the table -- no
    offset constant), so e' = 0 for all x near 1: no e*ln2 cancellation.
    ln2 is split with a 42-significant-bit head so e*LN2_HI is exact for the
    entire reachable |e| <= 1075 range (42 + 11 bits <= 53).
    Series: Taylor log(1+t) = t + t^2*q(t), c_k = (-1)^(k+1)/k, degree 7
    (|t| <= 2^-8 => relative truncation ~ 2^-59; measured max 0.52 ULP).

Usage:  python3 -m venv .venv && .venv/bin/pip install mpmath
        .venv/bin/python scripts/gen_neon_log_cleanroom_table.py
Writes src/neon_log_cleanroom_data.inc relative to the repo root.
"""

import math
import os
import struct

import mpmath as mp

mp.mp.prec = 300

N = 128
K = N.bit_length() - 1
POLY_DEG = 7  # total series degree; coefficients c2..c_deg


def dbits(f: float) -> int:
    return struct.unpack("<Q", struct.pack("<d", f))[0]


def to_double(x: mp.mpf) -> float:
    return float(x)


def hexf(f: float) -> str:
    if f == 0.0 and math.copysign(1.0, f) > 0:
        return "0x0p+0"
    return float.hex(f)


# --- ln2 compensated pair: 42-bit head => e*LN2_HI exact for |e| <= 1075 ----
LN2_MP = mp.log(2)
LN2_HI = to_double(mp.mpf(int(mp.nint(LN2_MP * 2**42))) / 2**42)
LN2_LO = to_double(LN2_MP - mp.mpf(LN2_HI))
assert LN2_HI * 2**42 == float(int(LN2_HI * 2**42)), "LN2_HI not 42-bit"
_ihi = int(LN2_HI * 2**42)
for e in (-1075, -1074, -64, -1, 1, 1023, 1024):
    assert abs(e * _ihi) < 2**53, "e*LN2_HI would not be exact"
assert abs(LN2_MP - mp.mpf(LN2_HI) - mp.mpf(LN2_LO)) < mp.mpf(2) ** -95

# --- anchor table -----------------------------------------------------------
SQRT2 = mp.sqrt(2)
CUT = int(mp.nint(N * (SQRT2 - 1)))
rows = []
stats = []
for j in range(N + 1):
    r = mp.mpf(1) + mp.mpf(j) / N
    R = to_double(1 / r)
    Lex = -mp.log(mp.mpf(R))  # exact log of the STORED double
    if j >= CUT:
        Lex = Lex - LN2_MP
    Lhi = to_double(Lex)
    Llo = to_double(Lex - mp.mpf(Lhi))
    assert abs(Lex - mp.mpf(Lhi) - mp.mpf(Llo)) < mp.mpf(2) ** -104
    rows.append((Lhi, Llo, R))
    half = mp.mpf(1) / (2 * N)
    mlo = max(mp.mpf(1), r - half)
    mhi = min(mp.mpf(2), r + half)
    tmax = max(abs(mlo * mp.mpf(R) - 1), abs(mhi * mp.mpf(R) - 1))
    stats.append((abs(Lex), tmax))

# exact endpoints: the near-1 guarantee (pure-series degeneration)
assert rows[0] == (0.0, 0.0, 1.0), rows[0]
assert rows[N] == (0.0, 0.0, 0.5), rows[N]
# Fast2Sum ordering precondition: wherever L != 0, |L| must exceed cell max|t|
margin = min((L / t) for (L, t) in stats[1:N] if L > 0)
assert margin > 1.9, f"Fast2Sum ordering margin violated: {margin}"
assert max(L for (L, _) in stats) < 0.35

TAYLOR_C = [to_double(mp.mpf((-1) ** (k + 1)) / k) for k in range(2, POLY_DEG + 1)]

# --- emit -------------------------------------------------------------------
root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
out = os.path.join(root, "src", "neon_log_cleanroom_data.inc")
with open(out, "w") as f:
    f.write("// Auto-generated by scripts/gen_neon_log_cleanroom_table.py -- do not edit.\n")
    f.write("// Clean-room derived anchor table for vector_log_neon; no third-party\n")
    f.write("// source (see docs/NEON_LOG_DERIVATION.md, docs/NEON_LOG_DIVERGENCE_AUDIT.md).\n\n")
    f.write(f"static constexpr int kLogNeonTblK = {K};    // N = 2^K = {N}\n")
    f.write(f"static constexpr int kLogNeonTblCut = {CUT};  // round(N*(sqrt2-1))\n")
    f.write(f"static constexpr double kLogNeonLn2Hi = {hexf(LN2_HI)};  // 42 significant bits\n")
    f.write(f"static constexpr double kLogNeonLn2Lo = {hexf(LN2_LO)};\n\n")
    f.write("// Taylor c2..c%d of log(1+t) = t + t^2*(c2 + c3*t + ...)\n" % POLY_DEG)
    f.write(f"static constexpr double kLogNeonC[{len(TAYLOR_C)}] = {{\n")
    for c in TAYLOR_C:
        f.write(f"    {hexf(c)},\n")
    f.write("};\n\n")
    f.write("// rows: {L_hi, L_lo, R, pad}; anchor r_j = 1 + j/%d; 64-byte aligned\n" % N)
    f.write("// (32-byte rows never straddle a cache line).\n")
    f.write(f"alignas(64) static const double kLogNeonCleanTable[{N + 1}][4] = {{\n")
    for (Lhi, Llo, R) in rows:
        f.write(f"    {{{hexf(Lhi)}, {hexf(Llo)}, {hexf(R)}, 0.0}},\n")
    f.write("};\n")

print(f"wrote {out}: N={N} (K={K}), CUT={CUT}, deg={POLY_DEG}, "
      f"Fast2Sum margin={mp.nstr(margin, 4)}")
